const types_color_dict = {
	"None" : "bbbbaa",
	"Bug" : "aabb22",
	"Dark" : "775544",
	"Dragon" : "7766ee",
	"Electric" : "ffcc33",
	"Fairy" : "ffaaff",
	"Fighting" : "bb5544",
	"Fire" : "ff4422",
	"Flying" : "6699ff",
	"Ghost" : "6666bb",
	"Grass" : "77cc55",
	"Ground" : "ddbb55",
	"Ice" : "77ddff",
	"Normal" : "bbbbaa",
	"Poison" : "aa5599",
	"Psychic" : "ff5599",
	"Rock" : "bbaa66",
	"Steel" : "aaaabb",
	"Water" : "3399ff"
};

const types_strong_against_dict = {
	"Bug" : "Dark;Grass;Psychic",
	"Dark" : "Ghost;Psychic",
	"Dragon" : "Dragon",
	"Electric" : "Flying;Water",
	"Fairy" : "Dark;Dragon;Fighting",
	"Fighting" : "Dark;Ice;Normal;Rock;Steel",
	"Fire" : "Bug;Grass;Ice;Steel",
	"Flying" : "Bug;Fighting;Grass",
	"Ghost" : "Ghost;Psychic",
	"Grass" : "Ground;Rock;Water",
	"Ground" : "Electric;Fire;Poison;Rock;Steel",
	"Ice" : "Dragon;Flying;Grass;Ground",
	"Normal" : "",
	"Poison" : "Fairy;Grass",
	"Psychic" : "Fighting;Poison",
	"Rock" : "Bug;Fire;Flying;Ice",
	"Steel" : "Fairy;Ice;Rock",
	"Water" : "Fire;Ground;Rock"
}

const types_weak_against_dict = {
	"Bug" : "Fairy;Fighting;Fire;Flying;Ghost;Poison;Steel",
	"Dark" : "Dark;Fairy;Fighting",
	"Dragon" : "Steel",
	"Electric" : "Dragon;Electric;Grass",
	"Fairy" : "Fire;Poison;Steel",
	"Fighting" : "Bug;Fairy;Flying;Poison;Psychic",
	"Fire" : "Dragon;Fire;Rock;Water",
	"Flying" : "Electric;Rock;Steel",
	"Ghost" : "Dark",
	"Grass" : "Bug;Dragon;Fire;Flying;Grass;Poison;Steel",
	"Ground" : "Bug;Grass",
	"Ice" : "Fire;Ice;Steel;Water",
	"Normal" : "Rock;Steel",
	"Poison" : "Ghost;Ground;Poison;Rock",
	"Psychic" : "Psychic;Steel",
	"Rock" : "Fighting;Ground;Steel",
	"Steel" : "Electric;Fire;Steel;Water",
	"Water" : "Dragon;Grass;Water"
};

const types_no_effect_dict = {
	"Bug" : "",
	"Dark" : "",
	"Dragon" : "Fairy",
	"Electric" : "Ground",
	"Fairy" : "",
	"Fighting" : "Ghost",
	"Fire" : "",
	"Flying" : "",
	"Ghost" : "Normal",
	"Grass" : "",
	"Ground" : "Flying",
	"Ice" : "",
	"Normal" : "Ghost",
	"Poison" : "Steel",
	"Psychic" : "Dark",
	"Rock" : "",
	"Steel" : "",
	"Water" : ""
};

const types_resists_dict = {
	"Bug" : "Fighting;Grass;Ground",
	"Dark" : "Dark;Ghost",
	"Dragon" : "Electric;Fire;Grass;Water",
	"Electric" : "Electric;Flying;Steel",
	"Fairy" : "Bug;Dark;Fighting",
	"Fighting" : "Bug;Dark;Rock",
	"Fire" : "Bug;Fairy;Fire;Grass;Ice;Steel",
	"Flying" : "Bug;Fighting;Grass",
	"Ghost" : "Bug;Poison",
	"Grass" : "Electric;Grass;Ground;Water",
	"Ground" : "Poison;Rock",
	"Ice" : "Ice",
	"Normal" : "",
	"Poison" : "Bug;Fairy;Fighting;Grass;Poison",
	"Psychic" : "Fighting;Psychic",
	"Rock" : "Fire;Flying;Normal;Poison",
	"Steel" : "Bug;Dragon;Fairy;Flying;Grass;Ice;Normal;Psychic;Rock;Steel",
	"Water" : "Fire;Ice;Steel;Water"
};

const types_weak_to_dict = {
	"Bug" : "Fire;Flying;Rock",
	"Dark" : "Bug;Fairy;Fighting",
	"Dragon" : "Dragon;Fairy;Ice",
	"Electric" : "Ground",
	"Fairy" : "Poison;Steel",
	"Fighting" : "Fairy;Flying;Psychic",
	"Fire" : "Ground;Rock;Water",
	"Flying" : "Electric;Ice;Rock",
	"Ghost" : "Dark;Ghost",
	"Grass" : "Bug;Fire;Flying;Ice;Poison",
	"Ground" : "Grass;Ice;Water",
	"Ice" : "Fighting;Fire;Rock;Steel",
	"Normal" : "Fighting",
	"Poison" : "Ground;Psychic",
	"Psychic" : "Bug;Dark;Ghost",
	"Rock" : "Fighting;Grass;Ground;Steel;Water",
	"Steel" : "Fighting;Fire;Ground",
	"Water" : "Electric;Grass"
};

const types_immune_to_dict = {
	"Bug" : "",
	"Dark" : "Psychic",
	"Dragon" : "",
	"Electric" : "",
	"Fairy" : "Dragon",
	"Fighting" : "",
	"Fire" : "",
	"Flying" : "Ground",
	"Ghost" : "Normal;Fighting",
	"Grass" : "",
	"Ground" : "Electric",
	"Ice" : "",
	"Normal" : "Ghost",
	"Poison" : "",
	"Psychic" : "",
	"Rock" : "",
	"Steel" : "Poison",
	"Water" : ""
};